name: LocateMe
description: A player location plugin that lets you get the coordinates of a player.
author: SleakGaming1
version: 1.0.1
main: SleakGaming1\LocateMe\LocateMe
api: 5.0.0
commands:
  coords:
    description: Get the coordinates of a player.
    usage: /coords <username>
    permission: locateme.command
permissions:
  locateme.command:
    default: op
